-- size of our actual window
WINDOW_WIDTH = 444
WINDOW_HEIGHT = 784

-- size we're trying to emulate with push
VIRTUAL_WIDTH = 1080
VIRTUAL_HEIGHT = 1920

PLAYER_SPEED = 1000

WEAPON_SPEED = 20

TIME_INTERVAL = 5
SHOOT_INTERVAL = 3